### ISSUE TITLE
GitHub organizations not respected

### ISSUE THREAD

**Issue by ManuelSchneid3r** [cachecleanerjeet/readme-stats-github#6]
Nice, but without the additions to github organizations the stats are meaningless

**Comment by tuhinpal** [comment]
This project is created only to showcase "my stats". I open sourced it in hope that people will contribute in this repository. And It got no contribution in 3+ years. That's why it is only being maintained and not any feature addition. 

Recently github-readme-stats had some problem thats why this repo is getting traffic. After some time this repository will be dead again.

But you can definitely add this feature and send me a PR, I will be grateful then.

Thank you! 😁

**Comment by ManuelSchneid3r** [comment]
Unfortunately this is totally not my tech stack. Np I understand that. Maybe somebody with the required skill will find some time. Regards

**Comment by tuhinpal** [comment]
OMG, you are the creator of albert launcher! Feel blessed that you created an issue. It was nice to talk with you 🙏🏻
